(:|node|
 (:|interface| (:@ (:|name| "org.freedesktop.DBus"))
	       (:|method| (:@ (:|name| "Hello"))
			  (:|arg| (:@ (:|direction| "out")
				      (:|type| "s"))))
	       (:|method| (:@ (:|name| "RequestName"))
			  (:|arg| (:@ (:|direction| "in")
				      (:|type| "s")))
			  (:|arg| (:@ (:|direction| "in")
				      (:|type| "u")))
			  (:|arg| (:@ (:|direction| "out")
				      (:|type| "u"))))
	       (:|method| (:@ (:|name| "ReleaseName"))
			  (:|arg| (:@ (:|direction| "in")
				      (:|type| "s")))
			  (:|arg| (:@ (:|direction| "out")
				      (:|type| "u"))))
	       (:|method| (:@ (:|name| "StartServiceByName"))
			  (:|arg| (:@ (:|direction| "in")
				      (:|type| "s")))
			  (:|arg| (:@ (:|direction| "in")
				      (:|type| "u")))
			  (:|arg| (:@ (:|direction| "out")
				      (:|type| "u"))))
	       (:|method| (:@ (:|name| "UpdateActivationEnvironment"))
			  (:|arg| (:@ (:|direction| "in")
				      (:|type| "a{ss}"))))
	       (:|method| (:@ (:|name| "NameHasOwner"))
			  (:|arg| (:@ (:|direction| "in")
				      (:|type| "s")))
			  (:|arg| (:@ (:|direction| "out")
				      (:|type| "b"))))
	       (:|method| (:@ (:|name| "ListNames"))
			  (:|arg| (:@ (:|direction| "out")
				      (:|type| "as"))))
	       (:|method| (:@ (:|name| "ListActivatableNames"))
			  (:|arg| (:@ (:|direction| "out")
				      (:|type| "as"))))
	       (:|method| (:@ (:|name| "AddMatch"))
			  (:|arg| (:@ (:|direction| "in")
				      (:|type| "s"))))
	       (:|method| (:@ (:|name| "RemoveMatch"))
			  (:|arg| (:@ (:|direction| "in")
				      (:|type| "s"))))
	       (:|method| (:@ (:|name| "GetNameOwner"))
			  (:|arg| (:@ (:|direction| "in")
				      (:|type| "s")))
			  (:|arg| (:@ (:|direction| "out")
				      (:|type| "s"))))
	       (:|method| (:@ (:|name| "ListQueuedOwners"))
			  (:|arg| (:@ (:|direction| "in")
				      (:|type| "s")))
			  (:|arg| (:@ (:|direction| "out")
				      (:|type| "as"))))
	       (:|method| (:@ (:|name| "GetConnectionUnixUser"))
			  (:|arg| (:@ (:|direction| "in")
				      (:|type| "s")))
			  (:|arg| (:@ (:|direction| "out")
				      (:|type| "u"))))
	       (:|method| (:@ (:|name| "GetConnectionUnixProcessID"))
			  (:|arg| (:@ (:|direction| "in")
				      (:|type| "s")))
			  (:|arg| (:@ (:|direction| "out")
				      (:|type| "u"))))
	       (:|method| (:@ (:|name| "GetAdtAuditSessionData"))
			  (:|arg| (:@ (:|direction| "in")
				      (:|type| "s")))
			  (:|arg| (:@ (:|direction| "out")
				      (:|type| "ay"))))
	       (:|method| (:@ (:|name| "GetConnectionSELinuxSecurityContext"))
			  (:|arg| (:@ (:|direction| "in")
				      (:|type| "s")))
			  (:|arg| (:@ (:|direction| "out")
				      (:|type| "ay"))))
	       (:|method| (:@ (:|name| "ReloadConfig"))
			  "")
	       (:|method| (:@ (:|name| "GetId"))
			  (:|arg| (:@ (:|direction| "out")
				      (:|type| "s"))))
	       (:|signal| (:@ (:|name| "NameOwnerChanged"))
			  (:|arg| (:@ (:|type| "s")))
			  (:|arg| (:@ (:|type| "s")))
			  (:|arg| (:@ (:|type| "s"))))
	       (:|signal| (:@ (:|name| "NameLost"))
			  (:|arg| (:@ (:|type| "s"))))
	       (:|signal| (:@ (:|name| "NameAcquired"))
			  (:|arg| (:@ (:|type| "s")))))
 (:|interface| (:@ (:|name| "org.freedesktop.DBus.Introspectable"))
	       (:|method| (:@ (:|name| "Introspect"))
			  (:|arg| (:@ (:|direction| "out")
				      (:|type| "s"))))))
